### ISSUE TITLE
Create GetDatasetByCategory functional requirements UML diagram

### ISSUE THREAD

**Issue by andrewbroekman** [CodingInfinity/Benchmark-Service-Documentation#61]

**Comment by andrewbroekman** [comment]
Realization relationship should be from interface to use case, not from use case to interface

**Comment by ReinhardtCromhout** [comment]
"Realization relationship should be from interface to use case, not from use case to interface"
I am confused by this since this diagram is done like all the others in the document.

**Comment by andrewbroekman** [comment]
Realization relationship should be pointing from interface to use case, not use case to interface. The other diagram made by other team members are also not correct. Remember the direction of the arrow should by what use case the contract is realized. Refer to mini project functional requirements. If other images in document persist, please create an issue to have them fixed as this is clearly incorrect.
